# Generated by Django 5.0.6 on 2024-06-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header_text', models.CharField(max_length=2000)),
                ('about_header_img', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Aboutsec1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as1title', models.CharField(max_length=200)),
                ('as1image1', models.FileField(upload_to='media/')),
                ('as1image2', models.FileField(default=None, upload_to='media/')),
                ('as1desc', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Aboutsec2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as2title', models.CharField(max_length=200)),
                ('as2image1', models.FileField(upload_to='media/')),
                ('as2image2', models.FileField(default=None, upload_to='media/')),
                ('as2desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bh_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='cartheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_header_img', models.FileField(upload_to='media/')),
                ('cart_header_imgname', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmname', models.CharField(max_length=120)),
                ('cmemail', models.CharField(max_length=120)),
                ('cmsubject', models.CharField(max_length=120)),
                ('cmmessage', models.CharField(max_length=12000)),
            ],
        ),
        migrations.CreateModel(
            name='contactheader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_header_title', models.CharField(blank=True, default='Contact Us', max_length=200, null=True)),
                ('contact_header_text', models.CharField(max_length=2000)),
                ('contact_header_img', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='contactmiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_middle_img', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Footerimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fimage', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Main_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=100)),
                ('menuurl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=120)),
                ('sdesc', models.CharField(max_length=120)),
                ('simage', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('pimage', models.FileField(upload_to='media/')),
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.IntegerField(max_length=10)),
                ('pdesc', models.CharField(max_length=500)),
                ('pstatus', models.CharField(max_length=500)),
                ('pweight_500gm', models.BooleanField(default=False)),
                ('pweight_1kg', models.BooleanField(default=False)),
                ('pweight_1_5kg', models.BooleanField(default=False)),
                ('pweight_2kg', models.BooleanField(default=False)),
                ('pweight_2_5kg', models.BooleanField(default=False)),
                ('pweight_3kg', models.BooleanField(default=False)),
                ('pweight_3_5kg', models.BooleanField(default=False)),
                ('pweight_4kg', models.BooleanField(default=False)),
                ('pweight_4_5kg', models.BooleanField(default=False)),
                ('pweight_5kg', models.BooleanField(default=False)),
                ('catfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinku_cakery_admin.category')),
            ],
        ),
    ]
