# Generated by Django 5.0.6 on 2024-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='password',
            new_name='adminpassword',
        ),
        migrations.RenameField(
            model_name='admindata',
            old_name='username',
            new_name='adminusername',
        ),
    ]
