# Generated by Django 5.0.6 on 2024-06-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0002_rename_password_admindata_adminpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=5000)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
