# Generated by Django 5.0.6 on 2024-06-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0003_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_address',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
