# Generated by Django 5.0.6 on 2024-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0004_alter_contact_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutheader',
            name='about_header_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsec1',
            name='as1desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsec2',
            name='as2desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bh_background',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartheader',
            name='cart_header_imgname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact_message',
            name='cmmessage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact_message',
            name='cmsubject',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactheader',
            name='contact_header_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdesc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='sdesc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='sname',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
