# Generated by Django 5.1.3 on 2024-12-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0005_alter_aboutheader_about_header_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pstatus',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
