# Generated by Django 5.0.6 on 2024-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_user', '0002_cart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
