# Generated by Django 5.0.6 on 2024-07-12 10:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_admin', '0004_alter_contact_address_mobile'),
        ('rinku_cakery_user', '0003_userprofile_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('weight', models.CharField(default=0, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(default=None)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinku_cakery_user.cart_data')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinku_cakery_admin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orders_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('weight', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(default=None)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinku_cakery_user.cart_data')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rinku_cakery_admin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
