# Generated by Django 5.0.6 on 2024-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_user', '0005_remove_orders_item_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_item',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
