# Generated by Django 5.0.6 on 2024-07-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_user', '0006_alter_orders_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_item',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders_item',
            name='message_on_cake',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
