# Generated by Django 5.0.1 on 2024-07-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rinku_cakery_user', '0007_orders_item_delivered_orders_item_message_on_cake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_item',
            name='message_on_cake',
        ),
        migrations.AddField(
            model_name='orders_item',
            name='message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
